export * from './index';
export { default as atencionSchema } from './atencionSchema';
export { default as especieSchema } from './especieSchema';
export { default as loginSchema } from './loginSchema';
export { default as mascotaSchema } from './mascotaSchema';
export { default as passwordSchema } from './passwordSchema';
export { default as practicaSchema } from './practicaSchema';
export { default as razaSchema } from './razaSchema';
export { default as usuarioSchema } from './usuarioSchema';
export { default as veterinarioSchema } from './veterinarioSchema';
